name: Playwright Tests with Allure Report

on:
  workflow_dispatch:  # Ручной запуск

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    # Установка зависимостей
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install --with-deps

    # Вытягивание предыдущей истории Allure
    - name: Download previous Allure history
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: gh-pages
      continue-on-error: true

    - name: Prepare history directory
      run: |
        mkdir -p allure-report/history
        if [ -d "gh-pages/history" ]; then
          cp -r gh-pages/history/* allure-report/history/
        fi

    # Запуск тестов
    - name: Run Playwright tests
      run: |
        pytest tests/ --alluredir=./allure-results
      continue-on-error: true

    # Генерация отчета Allure с историей
    - name: Generate Allure Report
      if: always()
      run: |
        npm install -g allure-commandline
        allure generate ./allure-results -o ./allure-report --clean

    # Копирование истории для следующего запуска
    - name: Copy new history
      if: always()
      run: |
        mkdir -p allure-report/history
        cp -r allure-report/history/* gh-pages/history/ 2>/dev/null || true

    # Деплой отчета и истории на GitHub Pages
    - name: Deploy Allure Report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
        keep_files: true  # Сохраняем существующие файлы (историю)

    # Сохранение результатов тестов как артефакт
    - name: Upload Allure Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results/
        retention-days: 7