name: Playwright Tests with Allure Report

on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    # Чекаут основного кода
    - uses: actions/checkout@v4

    # Установка Python и зависимостей
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install --with-deps

    # Скачивание предыдущей истории из gh-pages
    - name: Download previous Allure history
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages
      continue-on-error: true

    # Подготовка истории для генерации отчета
    - name: Prepare history directory
      run: |
        mkdir -p allure-report/history
        if [ -d "gh-pages/history" ]; then
          cp -r gh-pages/history/* allure-report/history/
          echo "History copied from gh-pages"
        else
          echo "No previous history found in gh-pages"
        fi
    # Отладка: проверка содержимого истории после копирования
    - name: Debug history after copy
      run: |
        ls -la allure-report/history || echo "History directory is empty after copy"

    # Запуск тестов
    - name: Run Playwright tests
      run: |
        pytest tests/ --alluredir=./allure-results
      continue-on-error: true

    # Отладка: проверка содержимого allure-results
    - name: Debug allure-results
      run: |
        ls -la allure-results || echo "allure-results directory is empty"

    # Генерация отчета Allure с историей
    - name: Generate Allure Report
      if: always()
      run: |
        npm install -g allure-commandline
        allure generate ./allure-results -o ./allure-report --clean

    # Отладка: проверка содержимого allure-report/history после генерации
    - name: Debug generated history
      run: |
        ls -la allure-report/history || echo "History directory is empty after generation"

    # Сохранение новой истории
    - name: Save new history
      if: always()
      run: |
        mkdir -p gh-pages/history
        cp -r allure-report/history/* gh-pages/history/
        echo "New history saved to gh-pages/history"

    # Отладка: проверка содержимого gh-pages/history перед деплоем
    - name: Debug saved history
      run: |
        ls -la gh-pages/history || echo "gh-pages/history is empty"

    # Деплой отчета и истории на GitHub Pages
    - name: Deploy Allure Report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./allure-report
        keep_files: true

    # Сохранение результатов тестов как артефакт
    - name: Upload Allure Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results/
        retention-days: 7