name: Playwright Pytest with Allure

on:
  workflow_dispatch:
#on:
#  push:
#    branches:
#      - main  # Set the branch, exp: main

jobs:
  download-history:
    runs-on: ubuntu-latest
    name: Download history
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install --with-deps
    - name: Download previous Allure history
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages
      continue-on-error: true
    - name: Prepare results with history
      run: |
        mkdir -p allure-results/history
        if [ -d "gh-pages/history" ]; then
          cp -r gh-pages/history/* allure-results/history/
          echo "History copied from gh-pages to allure-results/history"
        else
          echo "No previous history found"
        fi
        ls -la allure-results/history || echo "allure-results/history is empty"
    - name: Upload history artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-results-history  # Уникальное имя
        path: allure-results/
        retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs: download-history
    name: Testing
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install --with-deps
    - name: Download history artifact
      uses: actions/download-artifact@v4
      with:
        name: allure-results-history
        path: allure-results/
    - name: Run Playwright tests
      run: |
        pytest tests/ --alluredir=./allure-results
      continue-on-error: true
    - name: Check test results
      run: |
        ls -la allure-results || echo "No test results generated"
    - name: Upload test results artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-results-tests  # Уникальное имя
        path: allure-results/
        retention-days: 1

  generate-report:
    runs-on: ubuntu-latest
    needs: test
    name: Generate report
    steps:
    - uses: actions/checkout@v4
    - name: Download test results artifact
      uses: actions/download-artifact@v4
      with:
        name: allure-results-tests
        path: allure-results/
    - name: Generate Allure Report
      if: always()
      run: |
        npm install -g allure-commandline
        allure generate ./allure-results -o ./allure-report --clean
        ls -la allure-report/history || echo "No history in report"
    - name: Save new history
      if: always()
      run: |
        mkdir -p gh-pages/history
        cp -r allure-report/history/* gh-pages/history/
        ls -la gh-pages/history || echo "No history saved to gh-pages"
    - name: Upload report artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report  # Уникальное имя
        path: allure-report/
        retention-days: 1

  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    name: Report publication
    steps:
    - uses: actions/checkout@v4
    - name: Download report artifact
      uses: actions/download-artifact@v4
      with:
        name: allure-report
        path: allure-report/
    - name: Download test results artifact
      uses: actions/download-artifact@v4
      with:
        name: allure-results-tests
        path: allure-results/
    - name: Deploy Allure Report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./allure-report
        keep_files: true
    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results-final  # Уникальное имя
        path: allure-results/
        retention-days: 7