name: Q-Room Tests Manually

on:
  workflow_dispatch:
    inputs:
      allure:
        description: "How to run test?"
        required: true
        default: "Pytest only"
        type: choice
        options:
          - "Pytest only"
          - "Pytest with Allure report"

permissions:
  contents: write  # Нужно для публикации на GitHub Pages
  id-token: write  # Права для публикации артефактов

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Clone Repository
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: 3. Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps
          if [ "${{ inputs.allure }}" == "Pytest with Allure report" ]; then
            npm install -g allure-commandline
          fi

      - name: 4. Run Pytest Tests
        run: |
          if [ "${{ inputs.allure }}" == "Pytest with Allure report" ]; then
            pytest tests/ --alluredir=allure-results
          else
            pytest tests/
          fi

      - name: 5. Generate Allure Report (if enabled)
        if: inputs.allure == 'Pytest with Allure report'
        run: |
          allure generate allure-results -o allure-report --clean
          ls -l allure-report

      - name: 6. Upload Allure Report as Artifact
        if: inputs.allure == 'Pytest with Allure report'
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ github.run_id }}
          path: allure-report

      - name: 7. Download Allure Report History (if available)
        if: inputs.allure == 'Pytest with Allure report'
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: 8. Store Allure Report History
        if: inputs.allure == 'Pytest with Allure report'
        run: |
          mkdir -p allure-results/history
          cp -r allure-report/history/* allure-results/history/

      - name: 9. Deploy Allure Report to GitHub Pages with Trends
        if: inputs.allure == 'Pytest with Allure report'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: allure-report
          clean: true

      - name: 10. Upload Allure Report History as Artifact
        if: inputs.allure == 'Pytest with Allure report'
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-history
          path: allure-results/history
