name: Pytest Tests with Allure Trend

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Download previous Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results-previous
        continue-on-error: true

      - name: Run Pytest tests with Allure
        run: |
          pytest --alluredir=allure-results

      - name: Merge previous and current Allure results
        run: |
          mkdir -p allure-results
          cp -r allure-results-previous/* allure-results/ || true
          echo "Merged previous results for trend analysis."

      - name: Generate Allure Report
        run: |
          pip install allure-pytest
          wget -qO - https://github.com/allure-framework/allure2/releases/latest/download/allure-linux.zip | funzip > /usr/local/bin/allure
          chmod +x /usr/local/bin/allure
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure results for future trends
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 7

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 7